config/routes.rb
Rails.application.routes.draw do
  get 'store/index'
resources :products
resources :categories
resources :subcategories

 root 'store#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
    has_attached_file :photo, :styles => {  :thumb => "600x600#", :medium => "300x300#", :small => "160x160#"}
    has_attached_file :video_file
    validates_uniqueness_of :title
    validates_attachment_content_type :photo, :video_file, :content_type => %w(image/jpeg image/jpg  image/png video/mp4) 
    validates_presence_of :title, :description, :price, :photo, :video_file
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories= Category.all
	end

	def new
		@category= Category.new
	end

	def create
		@category= Category.new(category_params)
	@category.save
			redirect_to @category
	
end
	def show
		@category= Category.find(params[:id])
	end

	def edit
		@category= Category.find(params[:id])
	end

	def update
		@category= Category.find(params[:id])
		if @category.update(category_params)
			redirect_to @category
		else
			render "edit"
		end
	end

	def destroy
		@category= Category.find(params[:id])
		@category.destroy
		redirect_to categories_path
	end

	private
	def category_params
		params.require(:category).permit(:title, :description)
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products= Product.paginate(page: params[:page], per_page: 2)
	end
	def new
		@product= Product.new
	end
	def create
		@product= Product.new(product_params)
		if @product.save
		redirect_to @product
	else 
		render 'new'
	end
end
	def show
		@product= Product.find(params[:id])
	end
	def edit
		@product= Product.find(params[:id])
	end
	def update
		@product= Product.find(params[:id])
		if @product.update(product_params)
			redirect_to @product
		else
			render "edit"
		end
	end
	def load_subcat
  
  @category = Category.find(params[:category_id])

  @subcategories = @category.subcategories
  respond_to do |format|
    format.js
  end
end
	def destroy
		@product= Product.find(params[:id])
		@product.destroy
		redirect_to products_path
	end
	private
	def product_params
		params.require(:product).permit(:title, :description, :price, :photo, :video_file)
	end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
	def index
		@subcategories= Subcategory.all
	end
	def new
		@subcategory= Subcategory.new
	end
	def create
		@subcategory= Subcategory.new(subcategory_params)
		if @subcategory.save
			redirect_to @subcategory
		else
			render "new"
		end
	end
	def show
		@subcategory= Subcategory.find(params[:id])
	end
	def edit
		@subcategory= Subcategory.find(params[:id])
	end
	def update
		@subcategory= Subcategory.find(params[:id])
		if @subcategory.update(subcategory_params)
			redirect_to @subcategory
    else
    	render "edit"
    end
  end
  def destroy
  	@subcategory= Subcategory.find(params[:id])
  	@subcategory.destroy
  	redirect_to subcategory_path
  end
  private
  def subcategory_params
  	params.require(:subcategory).permit(:title, :category_id)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/categories/_form.html.erb
 <%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<p>
<strong>Title:</strong>
<%= @category.title %>
</p>
<p>
<strong>Description:</strong>
<%= @category.description %>
</p>
<%= link_to 'Edit', edit_category_path(@category) %> 
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>View</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
 <%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="visible-md visible-lg">
 <%= f.label :video_file %><br>
  <%= f.file_field :video_file %>
  </div><br />
<div class="field">
<%= f.label :photo %><br>
<%= f.file_field :photo %>
</div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<script>
  function select_file(val){
    $.ajax({
      url: "/products/load_subcat?category_id=" + val,
  });
  }
  </script>

app/views/products/_load_subcat.html.erb
 <div class="field">
    <%= select_tag :subcategory_id, options_for_select([["Select SubCategory"]] + @subcategories.map {|c| [c.title, c.id]}) %>
  </div>

app/views/products/edit.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @products %>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<%= image_tag @product.photo.url(:small) %>
<strong>Video_file:</strong>
<%= video_tag @product.video_file.url , :controls => :true  %>
</p>

  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> 
<%= link_to 'Back', products_path %>

app/views/store/index.html.erb
<h1>Store#index</h1>
<p>Find me in app/views/store/index.html.erb</p>

app/views/subcategories/_form.html.erb
<%= form_for(@subcategory) do |f| %>
<% if @subcategory.errors.any? %>
  <div class="da-panel-content">
    <div class="da-message warning">
      <h2><%= pluralize(@subcategory.errors.count, "error") %> prohibited this sub category from being saved:</h2>

      <ul>
        <% @subcategory.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="da-form-row">
  <label></label>
  <div class="da-form-item large">
    <%= f.select(:category_id, Category.all.map {|c| [c.title, c.id]}, :prompt =>"Choose a Category") %>
  </div>
</div>

<div class="da-form-row">
  <label><%= f.label :title %></label>
  <div class="da-form-item large">
    <%= f.text_field :title, class: "form-control", placeholder:"Name of SubCategory"%>
    </div>
  </div>

<div class="da-button-row">
    <%= f.submit class: "da-button blue left" %>
</div>

<% end %>

app/views/subcategories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing categories</h1>

<table>
	<thead>
		<tr>
			<th>Sub Cat</th>
			<th>Cat</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @subcategories.each do |subcategory| %>
		<tr>
			<td><%= subcategory.title %></td>
		  <td><%= link_to 'Destroy', subcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to 'New subcategory',new_subcategory_path() %>

app/views/subcategories/new.html.erb
<h1>New Subcategory</h1>

<%= render 'form' %>

app/views/subcategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @subcategory.title %>
</p>


<%= link_to 'Edit', edit_subcategory_path(@subcategory) %> 
<%= link_to 'Back', subcategories_path %>